variables:
  major: 2
  minor: 1
  system.debug: true
  # creates a counter called versioncounter and seeds it at 100 and then assigns the value to a variable named patch.
  patch: $[counter('patchversion', 100)]
stages:
- stage: dev
  jobs:
  - job: MyJob
    displayName: Dev Job
    continueOnError: true
    steps:
    - script: echo My dev job
- stage: QA1
  dependsOn: dev
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), eq(variables['patchversion'],'101'))
  jobs:
  - job: QAJob
    displayName: QA1
    continueOnError: true
    steps:
    - script: echo My QA1 job